package com.carboxhub.app;

public final class WebUi {
    private WebUi() {}
    public static String page(String token) {
        return "<!doctype html>\n" +
"<html lang='zh-CN'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>\n" +
"<title>CarBoxHub</title><style>\n" +
":root{color-scheme:dark;--bg:#0b1220;--card:#111827;--line:#263244;--muted:#94a3b8;--blue:#2563eb;--green:#16a34a;--red:#dc2626}*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#08111f,#111827);color:#e5e7eb;font:15px system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.wrap{max-width:1100px;margin:auto;padding:24px}.top{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.brand{font-size:25px;font-weight:800}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:16px;margin-top:18px}.card{background:rgba(17,24,39,.92);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 12px 32px #0004}.drop{border:2px dashed #40516b;border-radius:14px;padding:34px;text-align:center;cursor:pointer}.drop.drag{border-color:#60a5fa;background:#1d4ed822}.btn,button{border:0;border-radius:9px;padding:9px 13px;color:white;background:#334155;cursor:pointer}.primary{background:var(--blue)}.danger{background:var(--red)}.ok{color:#86efac}.bad{color:#fca5a5}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.space{justify-content:space-between}.progress{height:9px;background:#253044;border-radius:20px;overflow:hidden;margin-top:12px}.bar{height:100%;width:0;background:#3b82f6}.files{margin-top:12px}.file{padding:12px 0;border-top:1px solid var(--line);display:flex;justify-content:space-between;gap:10px;align-items:center}.tag{font-size:12px;padding:3px 7px;border:1px solid #475569;border-radius:99px}.np{font-size:20px;font-weight:700;margin-top:8px}.switch{display:inline-flex;align-items:center;gap:8px}.switch input{width:18px;height:18px}@media(max-width:800px){.grid{grid-template-columns:1fr}.wrap{padding:14px}}\n" +
"</style></head><body><div class='wrap'>\n" +
"<div class='top'><div><div class='brand'>CarBoxHub</div><div class='muted'>7862 车盒局域网文件与媒体桥接</div></div><div id='sys' class='muted'>加载中...</div></div>\n" +
"<div class='grid'><div class='card'><h3>传送文件 / APK</h3><div id='drop' class='drop'>拖文件到这里，或点击选择<input id='file' type='file' hidden></div><div class='row' style='margin-top:12px'><button id='upload' class='primary'>仅上传</button><button id='install'>上传并安装 APK</button><span id='sel' class='muted'>未选择文件</span></div><div class='progress'><div id='bar' class='bar'></div></div><div id='msg' class='muted' style='margin-top:8px'></div><h3 style='margin-top:24px'>已上传文件</h3><div id='files' class='files'></div></div>\n" +
"<div><div class='card'><h3>网易云媒体投送</h3><label class='switch'><input id='netease' type='checkbox'>启用插件</label><div id='np' class='np'>暂无媒体</div><div id='artist' class='muted'></div><div id='mediaState' class='muted' style='margin-top:10px'></div><p class='muted'>目标包：com.netease.cloudmusic.iot / com.netease.cloudmusic</p></div>\n" +
"<div class='card' style='margin-top:16px'><h3>系统设置</h3><label class='switch'><input id='rootInstall' type='checkbox'>有 root 时优先静默安装</label><br><label class='switch' style='margin-top:10px'><input id='autoStart' type='checkbox'>开机自动启动</label><div id='installPerm' class='muted' style='margin-top:12px'></div></div></div></div></div>\n" +
"<script>const TOKEN='" + token + "';const H={'X-CarBox-Token':TOKEN};let selected=null;const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]));const enc=s=>encodeURIComponent(s).replace(/'/g,'%27');function fmt(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'}\n" +
"async function api(path,opt={}){opt.headers=Object.assign({},opt.headers||{},H);let r=await fetch(path,opt);let t=await r.text();try{return JSON.parse(t)}catch(e){throw new Error(t)}}\n" +
"async function refresh(){let s=await api('/api/status');$('#sys').textContent=s.ip+':'+s.port+' · v'+s.version+(s.rootAvailable?' · ROOT':'')+' · '+s.storagePath;$('#rootInstall').checked=s.rootInstall;$('#autoStart').checked=s.autoStart;$('#installPerm').innerHTML=s.canRequestPackageInstalls?'APK 安装权限：<span class=ok>可用</span>':'APK 安装权限：<span class=bad>需要在车盒端允许“安装未知应用”</span>';let p=s.plugins.find(x=>x.id==='netease_media');if(p){$('#netease').checked=p.enabled;let n=p.state.nowPlaying||{};$('#np').textContent=n.title||'暂无媒体';$('#artist').textContent=[n.artist,n.album].filter(Boolean).join(' · ');$('#mediaState').innerHTML='通知使用权：'+(p.state.notificationAccess?'<span class=ok>已授权</span>':'<span class=bad>未授权，请在车盒端开启</span>')+' · '+(n.playing?'播放中':'暂停/空闲')+(p.state.lastError?' · '+esc(p.state.lastError):'')}await files()}\n" +
"async function files(){let d=await api('/api/files');$('#files').innerHTML=d.files.length?d.files.map(f=>`<div class=file><div><b>${esc(f.name)}</b><div class=muted>${fmt(f.size)} ${f.apk&&f.apk.valid?' · '+esc(f.apk.packageName)+' '+esc(f.apk.versionName)+(f.apk.selfUpdate?' · <span class=ok>CarBoxHub 更新包</span>':''):''}</div></div><div class=row>${f.apk&&f.apk.valid?`<button onclick=installFile('${enc(f.name)}')>安装</button>`:''}<button onclick=downloadFile('${enc(f.name)}')>下载</button><button class=danger onclick=delFile('${enc(f.name)}')>删除</button></div></div>`).join(''):'<div class=muted>暂无文件</div>'}\n" +
"function choose(f){selected=f;$('#sel').textContent=f?f.name+' · '+fmt(f.size):'未选择文件'}$('#drop').onclick=()=>$('#file').click();$('#file').onchange=e=>choose(e.target.files[0]);['dragenter','dragover'].forEach(x=>$('#drop').addEventListener(x,e=>{e.preventDefault();$('#drop').classList.add('drag')}));['dragleave','drop'].forEach(x=>$('#drop').addEventListener(x,e=>{e.preventDefault();$('#drop').classList.remove('drag')}));$('#drop').addEventListener('drop',e=>choose(e.dataTransfer.files[0]));\n" +
"function upload(install){if(!selected)return alert('先选择文件');if(install&&!selected.name.toLowerCase().endsWith('.apk'))return alert('“上传并安装”只接受 APK');let x=new XMLHttpRequest();x.open('POST','/api/upload?filename='+encodeURIComponent(selected.name)+'&install='+(install?1:0));x.setRequestHeader('X-CarBox-Token',TOKEN);x.upload.onprogress=e=>{if(e.lengthComputable)$('#bar').style.width=(e.loaded/e.total*100).toFixed(1)+'%'};x.onload=()=>{$('#msg').textContent=x.responseText;$('#bar').style.width='100%';refresh()};x.onerror=()=>$('#msg').textContent='上传失败';x.send(selected)}$('#upload').onclick=()=>upload(false);$('#install').onclick=()=>upload(true);\n" +
"async function installFile(n){let d=await api('/api/install?name='+n,{method:'POST'});alert(d.message||JSON.stringify(d));refresh()}async function delFile(n){if(!confirm('删除这个文件？'))return;await api('/api/delete?name='+n,{method:'POST'});files()}function downloadFile(n){location.href='/api/download?token='+encodeURIComponent(TOKEN)+'&name='+n}\n" +
"$('#netease').onchange=async e=>{await api('/api/plugin?id=netease_media&enabled='+(e.target.checked?1:0),{method:'POST'});refresh()};$('#rootInstall').onchange=async e=>{await api('/api/config?rootInstall='+(e.target.checked?1:0),{method:'POST'});refresh()};$('#autoStart').onchange=async e=>{await api('/api/config?autoStart='+(e.target.checked?1:0),{method:'POST'});refresh()};refresh();setInterval(refresh,3000)</script></body></html>";
    }
}
